export const FETCH_REBATES = 'FETCH_REBATES';
export const FETCH_REBATES_LOADING = 'FETCH_REBATES_LOADING';
export const FETCH_REBATES_SUCCESS = 'FETCH_REBATES_SUCCESS';
export const FETCH_REBATES_FAILURE = 'FETCH_REBATES_FAILURE';

export const ADD_REBATE = 'ADD_REBATE';
export const ADD_REBATE_LOADING = 'ADD_REBATE_LOADING';
export const ADD_REBATE_SUCCESS = 'ADD_REBATE_SUCCESS';
export const ADD_REBATE_FAILURE = 'ADD_REBATE_FAILURE';

export const PERSIST_TABLE = 'PERSIST_TABLE';
