export const FETCH_REBATES = 'FETCH_REBATES';
export const FETCH_REBATES_LOADING = 'FETCH_REBATES_LOADING';
export const FETCH_REBATES_SUCCESS = 'FETCH_REBATES_SUCCESS';
export const FETCH_REBATES_FAILURE = 'FETCH_REBATES_FAILURE';

export const CREATE_REBATE = 'CREATE_REBATE';
export const CREATE_REBATE_LOADING = 'CREATE_REBATE_LOADING';
export const CREATE_REBATE_SUCCESS = 'CREATE_REBATE_SUCCESS';
export const CREATE_REBATE_FAILURE = 'CREATE_REBATE_FAILURE';
