export const FETCH_REBATES = 'FETCH_REBATES';
export const FETCH_REBATES_LOADING = 'FETCH_REBATES_LOADING';
export const FETCH_REBATES_SUCCESS = 'FETCH_REBATES_SUCCESS';
export const FETCH_REBATES_FAILURE = 'FETCH_REBATES_FAILURE';

//export const FETCH_REBATE = 'FETCH_REBATE';
export const FETCH_REBATE_LOADING = 'FETCH_REBATE_LOADING';
export const FETCH_REBATE_SUCCESS = 'FETCH_REBATE_SUCCESS';
export const FETCH_REBATE_FAILURE = 'FETCH_REBATE_FAILURE';

export const GET_REBATE = 'GET_REBATE';
export const ADD_REBATE = 'ADD_REBATE';
export const REMOVE_REBATE = 'REMOVE_REBATE';
export const UPDATE_REBATE = 'UPDATE_REBATE';
export const CREATE_REBATE = 'CREATE_REBATE';
export const SAVE_REBATE = 'SAVE_REBATE';
