export const TOGGLE_BUILDER_MODE = 'TOGGLE_BUILDER_MODE';
export const TOGGLE_QUERY_PANEL = 'TOGGLE_QUERY_PANEL';
export const TOGGLE_INPUT_TEXT = 'TOGGLE_INPUT_TEXT';
export const SET_OVERLAY = 'SET_OVERLAY';
