export const FETCH_INVESTORS = 'FETCH_INVESTORS';
export const FETCH_INVESTORS_LOADING = 'FETCH_INVESTORS_LOADING';
export const FETCH_INVESTORS_SUCCESS = 'FETCH_INVESTORS_SUCCESS';
export const FETCH_INVESTORS_FAILURE = 'FETCH_INVESTORS_FAILURE';